### ISSUE TITLE
Music not showing in ncmpcpp

### ISSUE THREAD

**Issue by JacobKauffman** [zX3no/ncmpcpp-windows#2]
I am pretty sure I did everything correct and it looks like ncmpcpp is connected to mpd but I just don't see my music library.

My mpd config:
bind_to_address "192.168.68.52"
port "6600"

music_directory "F:/Media/Music"
log_file "C:/mpd/mpd.log"
db_file "C:/mpd/mpd.db"
playlist_directory "C:/mpd/playlists"
state_file "C:/mpd/mpdstate"
pid_file "C:/mpd/mpd.pid"

audio_output {
    type "winmm"
    name "Headphones"
    mixer_type "software"
    device "Headphones (JBL E55BT Stereo)"
}

My ncmpcpp config:
mpd_host = "192.168.68.52"
mpd_port = 6600
media_library_primary_tag = album_artist

What am I doing wrong?

**Comment by zfphex** [comment]
Did you press `u` to update the music library?

**Comment by JacobKauffman** [comment]
> Did you press `u` to update the music library?

Yes I did

**Comment by zfphex** [comment]
So just to confirm. 
You open ncmpcpp and it says "Connected to 192.168.68.52" at the bottom right. 
You press `u` to update your media library and it says "Database update finished".
You press `4` to go to your media library and there is nothing there.

If this is the case, first we need to figure out if mpd is working correctly.

1. Close all instances of mpd by running `taskkill /IM mpdw.exe /f` and `taskkill /IM mpd.exe /f`.
2. Open mpd with a terminal using `mpd mpd.conf` and make sure there are no errors like: `Jan 17 14:06 : exception: Failed to access F:/Media/Music: The system cannot find the file specified. No such file or directory`
3. Open WSL and install `mpc` using `sudo apt install mpc`
4. Run `mpc update -h 192.168.68.52` and `mpc stats -h 192.168.68.52`. 
If there are no albums, artists or songs, then mpd is unable to read your music directory. 
If this is the issue, try setting your music folder to a different drive and test with a handful of songs.

If ncmpcpp is your problem, ¯\\_(ツ)_/¯. You could try my [new music player](https://github.com/zX3no/gonk).

**Comment by JacobKauffman** [comment]
I'm really dumb, pressing 4 fixed it. Oh one more thing, the visualizer isn't working. Any clue why or how to fix that?

**Comment by zfphex** [comment]
I think you need to add this to your `mpd.conf`.

```
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "C:/mpd/mpd.fifo"
    format                  "44100:16:2"
}
```

**Comment by JacobKauffman** [comment]
Well I think you're right but I get this

Jan 16 21:13 : exception: nested: No such audio output plugin: fifo

Is there a way I can install the FIFO plugin?

**Comment by zfphex** [comment]
I just remembered it doesn't work on windows.

You can run mpd on ubuntu along side ncmpcpp. WSL-G will allow audio to work. I'm sure there is a reason I stopped using mpd like this, but I can't remember. 

My old config was something like this.
```
 bind_to_address "127.0.0.1"
 music_directory "/mnt/d/onedrive/music"
 playlist_directory "~/.mpd/playlists"   
 db_file      "~/.mpd/mpd.db"  
 log_file      "~/.mpd/mpd.log"  
 pid_file      "~/.mpd/mpd.pid"  
 state_file     "~/.mpd/mpdstate"  

 audio_output {  
     type  "pulse"  
     name  "pulse audio"
     device         "pulse" 
     mixer_type      "hardware" 
 }  

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
```

**Comment by JacobKauffman** [comment]
Ok, thanks for all the help

**Comment by zfphex** [comment]
No problem. 👍
